


```{r}

library(tidyverse)
library(usdata)

```


```{r}

rosters23 <- read_csv("https://github.com/dwillis/wbb-rosters/raw/main/rosters_2022-23.csv")


```

# Things to clean
--> Standardize Positions (G, Guard, Guard/Forward)
--> Extract state and standardize (TX, Texas)
--> Drop where Name is NA
--> Standardize Year (Fy, Freshman, Fr., Redshirt Freshman)
--> Standardize Height (5'10" or 5-10)

# Columns to add
--> State
--> Country

```{r}

rosters23 %>% distinct(hometown) %>% arrange(hometown)

rosters23_clean <- rosters23 %>% 
  mutate(hometown_clean = str_to_lower(hometown))

rosters23_clean <- rosters23_clean %>% separate(hometown_clean, c("new_hometown", "state"), sep = ",", extra = "merge")

#rosters23_clean <- rosters23_clean %>% separate(col=hometown_clean, into-c("new_hometown", "state"), sep = ",", extra = "merge")

```

```{r}

rosters23_clean <- rosters23_clean %>% 
  mutate(state = str_trim(state), state = str_replace(state, '\\.','')) %>% 
  mutate(state = case_when(
     is.na(abbr2state(state)) ~ state,
     TRUE ~ str_to_lower(abbr2state(state)))
  )


```





#clean positions
```{r}


rosters23_clean <- rosters23_clean %>% 
  mutate(pos_clean = str_to_lower(str_trim(position)))

rosters23_clean$pos_clean <- gsub('guard', 'g', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('wing', 'w', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('gu', 'g', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('foward', 'f', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('fwd', 'f', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('fy', 'f', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('forward', 'f', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('center', 'c', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('gaurd', 'g', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('forawrd', 'f', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub(' ', '', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('-', '/', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('forard', 'f', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('f.', 'f', rosters23_clean$pos_clean)
rosters23_clean$pos_clean <- gsub('point', 'p', rosters23_clean$pos_clean)

  

rosters23_clean %>% distinct(pos_clean) %>% arrange(pos_clean)


  

```


##Clean Year 

```{r}

rosters23 %>%  
  group_by(year) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

```

```{r}
wbb <- read_csv("https://github.com/dwillis/wbb-rosters/raw/main/rosters_2022-23.csv")
```

```{r}
years_cleaned <- read_csv("years_cleaned.csv")
wbb <- inner_join(wbb, years_cleaned)
wbb <- wbb %>%
  select(-count)



```
#High schools to previous schools

```{r}

hs_wbb <- wbb %>%
  filter(is.na(high_school))%>%
  filter(!is.na(previous_school))%>%
  filter(str_detect(previous_school, "HS"))%>%
  mutate(hs_clean = "")%>%
  mutate(hs_clean = previous_school)%>%
  mutate(type = "has hs")


extras_wbb <- wbb %>%
  filter(!is.na(high_school))%>%
  filter(is.na(previous_school))%>%
  #filter(!str_detect(previous_school, "HS"))%>%
  #filter(!str_detect(previous_school, "HS"))%>%
  mutate(hs_clean = "")%>%
  mutate(type = "no hs")

all_wbb <- bind_rows(hs_wbb, extras_wbb)

#we should be able to bind rows because these dfs should be at odds with each other, and we just want to stack them on top of each other

```


#A case when approach to high schools
```{r}
list=as.list(hs_wbb$previous_school)

wbb <- wbb %>%
  mutate(hs_clean = "")%>%
  case_when(
    is.na(high_school) && previous_school %in% list ~
    mutate(hs_clean = high_school))



if previous school is in the list and high school is NA
  put previous school in high school 

```







